kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# this is for insecure docker registry
containerdConfigPatches: 
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
    endpoint = ["http://kind-registry:5000"]
####################################################################
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      "service-node-port-range": "30600-30699"
networking:
  apiServerAddress: "10.88.33.144"
  apiServerPort: 6444
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30600
        hostPort: 30600
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
        protocol: tcp # Optional, defaults to tcp
      - containerPort: 30601
        hostPort: 30601
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30602
        hostPort: 30602
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30603
        hostPort: 30603
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30604
        hostPort: 30604
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30605
        hostPort: 30605
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30606
        hostPort: 30606
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30607
        hostPort: 30607
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30608
        hostPort: 30608
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30609
        hostPort: 30609
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30610
        hostPort: 30610
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30611
        hostPort: 30611
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30612
        hostPort: 30612
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30613
        hostPort: 30613
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30614
        hostPort: 30614
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30615
        hostPort: 30615
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30616
        hostPort: 30616
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30617
        hostPort: 30617
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30618
        hostPort: 30618
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30619
        hostPort: 30619
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30620
        hostPort: 30620
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30621
        hostPort: 30621
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30622
        hostPort: 30622
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30623
        hostPort: 30623
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30624
        hostPort: 30624
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30625
        hostPort: 30625
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30626
        hostPort: 30626
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30627
        hostPort: 30627
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30628
        hostPort: 30628
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30629
        hostPort: 30629
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30630
        hostPort: 30630
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30631
        hostPort: 30631
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30632
        hostPort: 30632
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30633
        hostPort: 30633
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30634
        hostPort: 30634
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30635
        hostPort: 30635
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30636
        hostPort: 30636
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30637
        hostPort: 30637
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30638
        hostPort: 30638
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30639
        hostPort: 30639
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30640
        hostPort: 30640
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30641
        hostPort: 30641
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30642
        hostPort: 30642
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30643
        hostPort: 30643
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30644
        hostPort: 30644
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30645
        hostPort: 30645
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30646
        hostPort: 30646
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30647
        hostPort: 30647
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30648
        hostPort: 30648
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30649
        hostPort: 30649
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30650
        hostPort: 30650
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30651
        hostPort: 30651
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30652
        hostPort: 30652
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30653
        hostPort: 30653
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30654
        hostPort: 30654
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30655
        hostPort: 30655
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30656
        hostPort: 30656
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30657
        hostPort: 30657
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30658
        hostPort: 30658
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30659
        hostPort: 30659
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30660
        hostPort: 30660
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30661
        hostPort: 30661
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30662
        hostPort: 30662
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30663
        hostPort: 30663
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30664
        hostPort: 30664
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30665
        hostPort: 30665
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30666
        hostPort: 30666
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30667
        hostPort: 30667
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30668
        hostPort: 30668
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30669
        hostPort: 30669
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30670
        hostPort: 30670
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30671
        hostPort: 30671
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30672
        hostPort: 30672
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30673
        hostPort: 30673
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30674
        hostPort: 30674
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30675
        hostPort: 30675
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30676
        hostPort: 30676
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30677
        hostPort: 30677
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30678
        hostPort: 30678
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30679
        hostPort: 30679
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30680
        hostPort: 30680
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30681
        hostPort: 30681
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30682
        hostPort: 30682
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30683
        hostPort: 30683
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30684
        hostPort: 30684
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30685
        hostPort: 30685
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30686
        hostPort: 30686
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30687
        hostPort: 30687
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30688
        hostPort: 30688
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30689
        hostPort: 30689
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30690
        hostPort: 30690
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30691
        hostPort: 30691
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30692
        hostPort: 30692
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30693
        hostPort: 30693
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30694
        hostPort: 30694
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30695
        hostPort: 30695
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30696
        hostPort: 30696
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30697
        hostPort: 30697
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30698
        hostPort: 30698
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30699
        hostPort: 30699
        listenAddress: "0.0.0.0"
        protocol: tcp
  - role: worker